// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hibrfnhcrropdocyvmjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpYnJmbmhjcnJvcGRvY3l2bWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDk4NjcsImV4cCI6MjA2ODkyNTg2N30.CEDD-V-JQFgr-7Zs0vTIu9uoOSj4FBX4ErjUWXkNTQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});